variable "vpc_name" {}
variable "vpc_cidr" {}
variable "environment" {}
variable "subnet_count" {}
variable "sg_name" {}
variable "ami_id" {}
variable "instance_type" {}
variable "ec2_name" {}
variable "project_name" {}
variable "bucket_name" {}
variable "log_group_name" {}
variable "retention_days" {}
variable "role_name" {}
variable "assume_service" {}
variable "policy_arn" {}
variable "trail_name" {}
variable "s3_bucket_name" {}
variable "route_table_name" {}
