variable "name" {}
variable "environment" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "security_groups" {}
variable "target_port" {}
variable "target_protocol" {}
variable "listener_port" {}
variable "listener_protocol" {}
variable "load_balancer_type" {}